### ISSUE TITLE
Z-Fikar

### ISSUE THREAD

**Issue by Z-Fikar** [BesutKode/uni-task-1#13]
First of all, I don't know if Weblate have merged my fixings or not.

https://github.com/BesutKode/uni-task-1/wiki/Z-Fikar

**Comment by jayvdb** [comment]
https://github.com/unknown-horizons/unknown-horizons/commit/7b9aed499a809 = 20+ detected & fixed. :+1:

How is https://github.com/Z-Fikar/Cek-Kamus detecting bugs that are not found by https://github.com/mamat-rahmat/checker_id ?  As far as I can see, the only differences are:
- your program is using a static data file, as opposed to an online API
- your output is slightly more helpful for the reader

But those alone dont meet the criteria of "The detected problem must not be able to be detected by any of the existing tools."

Maybe there is some additional information in https://github.com/bgli/kbbi-qt/blob/master/data-src/kbbi_data.csv that you can extract to detect different translation bugs?  i.e. More specific grammar rules rather than detecting unknown words / spelling mistakes.

**Comment by Z-Fikar** [comment]
I actually convert `kbbi_data.csv` to `kamus.txt` but only take the words

**Comment by jayvdb** [comment]
Yea, I could see the conversion process you used.
However if you only use the words from `kbbi_data.csv`, your tool is finding the same bugs as  @arrizalamin 's and @mamat-rahmat 's tool, as it is the same word list and stemmer .
You need to add something, to build on what they have done.  Maybe the third column of `kbbi_data.csv` can be useful - I am only offering that as a suggestion.  There are many other ways your tool might be improved to pick up translations bugs not found by the existing tools.

**Comment by Z-Fikar** [comment]
How about now? I kinda give it a suggestion feature.

**Comment by jayvdb** [comment]
There were some syntax errors in the Python code, but easily fixed. :+1:
