### ISSUE TITLE
sanAkdam

### ISSUE THREAD

**Issue by sanakdam** [BesutKode/uni-task-1#20]
https://github.com/BesutKode/uni-task-1/wiki/sanAkdam

**Comment by jayvdb** [comment]
# openSUSE/libgnomesu

:-1: Smart quotes are a linguistic element.  Some languages require them.

Extra information in brackets are intentional effort by translators to help the reader understand terms which do not have a well-understood translation.

# fr3ts0n/AndrOBD

:-1: `acronyms` are a translation choice.  Not a bug.

# osmandapp/Osmand

```
# (pofilter) filepaths: Different file paths
msgid "Dojo / Martial Arts Academy"
msgstr "Harcművészeti edzőterem - dojo"
```

:-1:  Does "Dojo / Martial Arts Academy" look like a file path to you?

```
# (pofilter) singlequoting: Different quotation marks
# (pofilter) startpunc: Different punctuation at the start
# (pofilter) startcaps: Different capitalization at the start
msgid "Bathroom Furnishing Store"
msgstr "' Fürdőszoba-felszerelés és -fürdőszobabútor bolt'"

# (pofilter) singlequoting: Different quotation marks
# (pofilter) startpunc: Different punctuation at the start
msgid "Copy Store"
msgstr "'Fénymásoló '"


# (pofilter) singlequoting: Different quotation marks
# (pofilter) startpunc: Different punctuation at the start
# (pofilter) startcaps: Different capitalization at the start
msgid "Food Bank"
msgstr "' Élelmiszerbank '"
```

:grey_question:  These extra whitespace look like translation bugs, but I am not 100% sure.  If you find 17 other translation fixes, I will accept these three to reach 20.

**Comment by jayvdb** [comment]
Incomplete.
